version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    parallelism: 1
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Build and Test Using Gradlew
          command: >
            chmod +x gradlew &&
            ./gradlew clean build test --no-daemon
      # Save cache for dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle.kts" }}
      # Upload builded jar file to artifact
      - persist_to_workspace:
          root: .
          paths:
            - build/libs/*.jar
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - attach_workspace:
          at: .
      # Create DockerFile From Jar
      - run:
          name: Create Dockerfile From Jar
          command: |
            cd build/libs
            JAR_FILE=$(ls *.jar | grep -v plain)
            echo "Using JAR_FILE=${JAR_FILE}"
            cd ../..
            echo "FROM openjdk:17-jdk" > Dockerfile
            echo "COPY build/libs/${JAR_FILE} /app.jar" >> Dockerfile
            echo "CMD [\"java\", \"-jar\", \"/app.jar\"]" >> Dockerfile
      # Build Docker image
      - run:
          name: Build Docker Image
          command: docker build -t $HEROKU_APP_NAME .
      # Download and cache dependencies
      - restore_cache:
          keys:
            - heroku-cli-cache
      - heroku/install
      # Save cache for dependencies
      - save_cache:
          paths:
            - /usr/local/bin/heroku
          key: heroku-cli-cache
      # Check Heroku Authentication
      - heroku/check-authentication:
          print-whoami: true

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - production
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - heroku-CD # for test

