version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    parallelism: 1
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run:
          name: Build and Test Using Gradlew
          command: >
            chmod +x gradlew &&
            ./gradlew clean build test --no-daemon
      # Save cache for dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v2-dependencies-{{ checksum "build.gradle.kts" }}
      # Upload builded jar file to artifact
      - store_artifacts:
          path: build/libs/
          destination: build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - production
                - github-CI
