name: Build and Test

on:
  pull_request:
    branches:
      - production
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          architecture: x64
          java-package: jdk

      - name: Build and test
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.pull_request.head.repo.name }}-${{ github.run_id }}
          path: build/libs/*.jar
