name: Build and Test

on:
  pull_request:
    branches:
      - production
      - master # for test

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: production

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Cache Load Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build and Test with Gradle
        run: ./gradlew build --info

      - name: Cache Save Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.pull_request.head.repo.name }}-${{ github.run_id }}
          path: build/libs/*.jar
