name: Build and Test

on:
  pull_request:
    branches:
      - production
      - master

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build --info

      - name: Test with Gradle
        run: ./gradlew test


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.pull_request.head.repo.name }}-${{ github.run_id }}
          path: build/libs/*.jar
