name: Build and Test

on:
  pull_request:
    branches:
      - production
      - master # for test

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 17

      - name: Gradle Cache Load
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build and Test with Gradle
        run: ./gradlew build --info

      - name: Gradle Cache Save
        uses: actions/cache@v3
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      # Restore cache for dependencies
      - name: AzureCLI Cache Load
        uses: actions/cache@v3
        with:
          path: /usr/bin/az
          key: azure-cli-dependency-cache

      # Install azure-cli
      - name: Download and Install azure-cli
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      # Build the application and upload to Azure Storage
      - name: Upload JAR to Azure Storage
        run: |
          FILE=$(find build/libs -name '*.jar' | grep -v 'plain')
          if [ -z "$FILE" ]; then
            echo "Plain jar file not found"
            exit 1
          elif az storage blob exists --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" --container-name "${{ secrets.AZURE_STORAGE_CONTAINER }}" --name "${FILE}" --output none; then
            az storage blob upload-batch --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" --destination "${{ secrets.AZURE_STORAGE_CONTAINER }}" --source build/libs --pattern "*.jar" --overwrite
          else
            az storage blob upload-batch --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" --destination "${{ secrets.AZURE_STORAGE_CONTAINER }}" --source build/libs --pattern "*.jar"
          fi

      # Save cache for dependencies
      - name: AzureCLI Cache Save
        uses: actions/cache@v3
        with:
          path: /usr/bin/az
          key: azure-cli-dependency-cache
