name: Deploy

on:
  pull_request:
    branches:
      - master # for deploy test
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Download the latest plain-less jar from Azure Storage
      - name: Download Latest JAR from Azure Storage
        run: |
          # Get the list of files
          FILES=$(az storage blob list --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" --container-name "${{ secrets.AZURE_STORAGE_CONTAINER }}" --query "[?contains(name, '-plain.jar') == \`false\`].name" -o tsv)
          
          # Find the latest version of the jar file
          LATEST=$(echo "$FILES" | grep -Eo '[0-9]+(\.[0-9]+)*' | sort -V | tail -n1)
          
          # Construct the file name
          FILE=$(echo "$FILES" | grep "$LATEST" | head -n1)
          if [ -z "$FILE" ]; then
            echo "Jar file not found"
            exit 1
          else
            # Download the file
            az storage blob download --account-name "${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" --account-key "${{ secrets.AZURE_STORAGE_ACCOUNT_KEY }}" --container-name "${{ secrets.AZURE_STORAGE_CONTAINER }}" --name "$FILE""
          fi

      # Deploy Downloaded JAR file to test port
      - name: "Test: execute downloaded jar file on 8080"
        run: nohup java -jar $FILE --server.port=8080 1>$FILE_test.log 2>$FILE_test.log &
      
      # Check JAR File works well on test port
      - name: "Test: service status check on test port"
        uses: pavelsaman/website-check@v2.3
        with:
          url: http://localhost:8080/status
          status_code: 200
          redirect: true

      # Kill test java process
      - name: "Test: terminate test process"
        run: sudo fuser -k 8080/tcp

      # Kill previous java process working on release port
      - name: Kill previous java process working on release port
        run: sudo fuser -k 5000/tcp

      # Deploy Downloaded JAR file to release port
      - name: Deploy Downloaded JAR File to Release Port
        run: nohup java -jar $FILE --server.port=5000 1>$FILE.log 2>$FILE_error.log &
