name: Deploy

on:
  pull_request:
    branches:
      - master # for deploy test
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check Online